# Welcome...

# Site settings
title: Amir Tabatabai
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my homepage!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown